# Use the official Node.js image based on Ubuntu
FROM node:14

# Set working directory
WORKDIR /app

# Install git
RUN apt-get update && apt-get install -y git

# Clone the frontend_dev branch of your repository
RUN git clone --single-branch --branch frontend_dev https://github.com/Rasmus-BK-Nielsen/DevOps_Demo.git .

# Change working directory to the frontend directory inside the cloned repository
WORKDIR /app/devops_frontend

# Install npm dependencies
RUN npm install

# Ensure startup script is Unix format
RUN sed -i 's/\r$//' startup_development.sh

# Make the startup script executable
RUN chmod +x startup_development.sh

# Expose the port the app runs on
EXPOSE 3000

# Start the development server
CMD ["./startup_development.sh"]
