name: CI
# REMEMBER! YML is very sensitive to indentation. Make sure to use spaces and not tabs!!!
# Trigger the workflow on push to the main branch and on pull requests to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
     runs-on: ubuntu-latest

     steps:
       - name: Checkout code
         uses: actions/checkout@v2
 
       # Set up Node.js and run JavaScript tests
       - name: Set up Node.js
         uses: actions/setup-node@v2
         with:
           node-version: '14'
 
       - name: Install dependencies
         run: |
           cd devops_frontend
           npm install
 
       - name: Run JavaScript tests
         run: |
           cd devops_frontend
           npm test

      # Set up .NET and run C# tests for backend
       - name: Set up .NET Core
         uses: actions/setup-dotnet@v1
         with:
           dotnet-version: '5.0.x'

       - name: Restore backend dependencies
         run: dotnet restore ./devops_backend/devops_backend.csproj

       - name: Build backend
         run: dotnet build ./devops_backend/devops_backend.csproj --no-restore

       - name: Run backend tests
         run: dotnet test ./devops_backend/devops_backend.csproj --no-build --verbosity normal
